import { spawnSync } from 'node:child_process';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { loadTasks, verifyTaskContract } from '../task-verifier/verify.js';
import { readState, refreshReady, writeState } from '../task-runner/state.js';

interface Queue { schemaVersion: '1.0.0'; taskIds: string[] }
const path = join(process.cwd(), 'artifacts/merge-queue/queue.json');
const readQueue = async (): Promise<Queue> => { try { return JSON.parse(await readFile(path, 'utf8')) as Queue; } catch { return { schemaVersion: '1.0.0', taskIds: [] }; } };
const writeQueue = async (queue: Queue): Promise<void> => { await mkdir(dirname(path), { recursive: true }); await writeFile(path, `${JSON.stringify(queue, null, 2)}\n`); };
const git = (args: string[]): string => { const result = spawnSync('git', args, { encoding: 'utf8' }); if (result.status !== 0) throw new Error(`GIT_FAILED:${args.join(':')}:${result.stderr.trim()}`); return result.stdout.trim(); };
const command = process.argv[2] ?? 'add'; const taskId = process.argv[3];
try { const tasks = await loadTasks(); const queue = await readQueue(); if (command === 'add') { if (!taskId || !tasks.some((task) => task.id === taskId)) throw new Error('VALID_TASK_ID_REQUIRED'); const state = await readState(tasks); if (state.tasks[taskId]?.state !== 'VERIFIED') throw new Error('TASK_NOT_VERIFIED'); if (!queue.taskIds.includes(taskId)) queue.taskIds.push(taskId); await writeQueue(queue); console.log(JSON.stringify(queue)); } else if (command === 'process') { const branch = git(['branch', '--show-current']); if (branch === 'main') throw new Error('DIRECT_MAIN_MERGE_PROHIBITED'); const next = queue.taskIds[0]; if (!next) throw new Error('MERGE_QUEUE_EMPTY'); const state = await readState(tasks); if (state.tasks[next]?.state !== 'VERIFIED') throw new Error('TASK_NOT_VERIFIED'); await verifyTaskContract(next); const taskBranch = `task/${next.toLowerCase()}`; git(['rebase', branch, taskBranch]); const commitCount = Number(git(['rev-list', '--count', `${branch}..${taskBranch}`])); if (commitCount !== 1) throw new Error('TASK_COMMIT_NOT_ATOMIC'); const commit = git(['rev-parse', taskBranch]); git(['merge', '--ff-only', taskBranch]); const integration = spawnSync('pnpm', ['test:integration'], { encoding: 'utf8' }); if (integration.status !== 0) { git(['revert', '--no-edit', commit]); throw new Error(`POST_MERGE_INTEGRATION_FAILED_REVERTED:${commit}`); } state.tasks[next]!.state = 'MERGED'; refreshReady(state, tasks); await writeState(state); queue.taskIds.shift(); await writeQueue(queue); console.log(JSON.stringify({ taskId: next, commit, status: 'MERGED' })); } else throw new Error(`UNKNOWN_COMMAND:${command}`); } catch (error) { console.error(JSON.stringify({ status: 'FAIL', error: error instanceof Error ? error.message : String(error) })); process.exitCode = 1; }
