import { spawnSync } from 'node:child_process';
import { access, mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { TaskContract } from '@ciag/shared-schemas';
import { acquire, assertLease, transition, type LifecycleDocument } from '../task-runner/state.js';

const git = (directory: string, args: string[]): string => { const result = spawnSync('git', args, { cwd: directory, encoding: 'utf8' }); if (result.status !== 0) throw new Error(`SIMULATION_GIT_FAILED:${args.join(':')}:${result.stderr.trim()}`); return result.stdout.trim(); };
const contract = (id: string, lock: string): TaskContract => ({ schemaVersion: '1.0.0', id, title: id, sourceHashes: { prd: 'a'.repeat(64), requirements: 'b'.repeat(64), audit: 'c'.repeat(64) }, dependencyGroup: 'G0', cluster: 'C-G0-X', riskLevel: 'LOW', autonomyLevel: 'AUTONOMOUS', dependencies: [], requirements: ['FR-X-001'], acceptanceCriteria: ['AC-001'], invariants: ['INV-001'], adrs: ['ADR-001'], ownerPackages: ['packages/x'], readSet: [], writeSet: ['packages/x/**'], allowedPaths: ['packages/x/**', 'tests/**'], forbiddenPaths: ['docs/spec/**'], exclusiveLocks: [lock], interfaceHashes: { x: 'd'.repeat(64) }, deliverables: ['x'], constraints: ['x'], nonGoals: ['x'], degradedBehavior: 'x', rollback: 'x', requiredTests: ['tests/x.spec.ts'], verificationCommands: [{ command: 'pnpm test', expected: 'exit 0' }], complexityBudget: { maxFiles: 1, maxChangedLines: 10, maxCyclomaticComplexity: 1 }, changeBudget: { maxMigrations: 0, maxPublicInterfaces: 0, requiresSplitAboveBudget: true }, stopConditions: ['x'], completionDefinition: ['x'], sourceReferences: [{ path: 'x', line: 1, id: 'FR-X-001' }] });

export const simulateGitLifecycle = async (): Promise<{ states: string[]; atomicCommits: number; staleLeaseRejected: boolean; lostLeaseRejected: boolean; pathLockRejected: boolean; rebaseApplied: boolean; injectedFailureDetected: boolean; failureCommitReverted: boolean; worktreeIsolated: boolean }> => {
  const root = await mkdtemp(join(tmpdir(), 'ciag-git-lifecycle-')); const repository = join(root, 'repository'); const taskWorktree = join(root, 'task-worktree'); await mkdir(repository);
  try {
    git(repository, ['init', '-b', 'cluster/g0']); git(repository, ['config', 'user.email', 'ciag-test@example.invalid']); git(repository, ['config', 'user.name', 'CIAG Test']); await writeFile(join(repository, 'baseline.txt'), 'baseline\n'); git(repository, ['add', 'baseline.txt']); git(repository, ['commit', '-m', 'chore: baseline']); git(repository, ['worktree', 'add', '-b', 'task/t-g0-simulation', taskWorktree, 'HEAD']); await writeFile(join(taskWorktree, 'task.txt'), 'task change\n'); git(taskWorktree, ['add', 'task.txt']); git(taskWorktree, ['commit', '-m', 'feat: atomic task']); await writeFile(join(repository, 'cluster.txt'), 'cluster advance\n'); git(repository, ['add', 'cluster.txt']); git(repository, ['commit', '-m', 'chore: advance cluster']); git(taskWorktree, ['rebase', 'cluster/g0']); const taskCommit = git(taskWorktree, ['rev-parse', 'HEAD']); const rebaseApplied = git(taskWorktree, ['rev-parse', 'HEAD^']) === git(repository, ['rev-parse', 'cluster/g0']); const atomicCommits = Number(git(repository, ['rev-list', '--count', 'cluster/g0..task/t-g0-simulation'])); git(repository, ['merge', '--ff-only', taskCommit]); const injectedFailure = spawnSync(process.execPath, ['-e', 'process.exit(42)'], { cwd: repository }); const injectedFailureDetected = injectedFailure.status === 42; if (injectedFailureDetected) git(repository, ['revert', '--no-edit', taskCommit]); let taskRemoved = false; try { await access(join(repository, 'task.txt')); } catch { taskRemoved = true; }
    const tasks = [contract('T-G0-A', 'same'), contract('T-G0-B', 'same')]; const state: LifecycleDocument = { schemaVersion: '1.0.0', tasks: { 'T-G0-A': { taskId: 'T-G0-A', state: 'READY', leaseVersion: 0 }, 'T-G0-B': { taskId: 'T-G0-B', state: 'READY', leaseVersion: 0 } } }; const states = [state.tasks['T-G0-A']?.state as string]; const lease = acquire(state, tasks, 'T-G0-A', 'worker', new Date('2026-01-01T00:00:00Z'), 1000); const target = state.tasks['T-G0-A']; if (!target) throw new Error('SIMULATION_TASK_STATE_MISSING'); states.push(target.state); transition(target, ['LEASED'], 'IMPLEMENTING'); states.push(target.state); transition(target, ['IMPLEMENTING'], 'SELF_REVIEWING'); states.push(target.state); transition(target, ['SELF_REVIEWING'], 'VERIFYING'); states.push(target.state); transition(target, ['VERIFYING'], 'VERIFIED'); states.push(target.state); transition(target, ['VERIFIED'], 'MERGE_QUEUED'); states.push(target.state); transition(target, ['MERGE_QUEUED'], 'MERGED'); states.push(target.state); let staleLeaseRejected = false; let lostLeaseRejected = false; let pathLockRejected = false; try { assertLease(state, 'T-G0-A', lease.version - 1, 'worker', new Date('2026-01-01T00:00:00Z')); } catch { staleLeaseRejected = true; } try { assertLease(state, 'T-G0-A', lease.version, 'worker', new Date('2026-01-01T00:00:02Z')); } catch { lostLeaseRejected = true; } target.state = 'LEASED'; try { acquire(state, tasks, 'T-G0-B', 'other', new Date('2026-01-01T00:00:00Z')); } catch { pathLockRejected = true; } states.push('REVERTED_AFTER_INTEGRATION_FAILURE');
    return { states, atomicCommits, staleLeaseRejected, lostLeaseRejected, pathLockRejected, rebaseApplied, injectedFailureDetected, failureCommitReverted: taskRemoved, worktreeIsolated: git(repository, ['worktree', 'list', '--porcelain']).includes(taskWorktree) };
  } finally { await rm(root, { recursive: true, force: true }); }
};
