import { createHash } from 'node:crypto';
import { readFile, readdir } from 'node:fs/promises';
import { join } from 'node:path';
import { TaskContractSchema, type TaskContract } from '@ciag/shared-schemas';
import { driftCheck, loadAndValidateSpecification, sha256 } from '../prd-compiler/compiler.js';
import { scanPlaceholders, scanProhibitedCapabilities, verifyArchitecture } from '../architecture-verifier/verify.js';

export interface CommandEvidence { command: string; exitCode: number; output: string; outputSha256: string }
export const deriveEvidenceVerdict = (requiredCommands: string[], evidence: CommandEvidence[]): 'PASS' => {
  for (const command of requiredCommands) { const item = evidence.find((candidate) => candidate.command === command); if (!item) throw new Error(`MISSING_COMMAND_EVIDENCE:${command}`); if (item.exitCode !== 0) throw new Error(`COMMAND_FAILED:${command}`); if (sha256(item.output) !== item.outputSha256) throw new Error(`FORGED_COMMAND_EVIDENCE:${command}`); if (/^(?:PASS|ok|true)$/i.test(item.output.trim())) throw new Error(`UNSUBSTANTIATED_COMMAND_EVIDENCE:${command}`); }
  return 'PASS';
};

export const loadTasks = async (): Promise<TaskContract[]> => { const tasks: TaskContract[] = []; for (let index = 0; index <= 7; index += 1) { const root = join(process.cwd(), `tasks/G${index}`); for (const file of await readdir(root)) if (file.endsWith('.contract.json')) tasks.push(TaskContractSchema.parse(JSON.parse(await readFile(join(root, file), 'utf8')))); } return tasks; };
export const verifyCoverage = async (): Promise<{ requirements: number; acceptanceCriteria: number; tasks: number }> => { const spec = await loadAndValidateSpecification(); const tasks = await loadTasks(); const requirementIds = new Set(tasks.flatMap((task) => task.requirements)); const acceptanceIds = new Set(tasks.flatMap((task) => task.acceptanceCriteria)); const missingRequirements = spec.manifest.requirements.filter((item) => !requirementIds.has(item.id)); const missingAcceptance = spec.manifest.acceptanceCriteria.filter((item) => !acceptanceIds.has(item.id)); if (missingRequirements.length || missingAcceptance.length) throw new Error(`INCOMPLETE_COVERAGE:R=${missingRequirements.length}:A=${missingAcceptance.length}`); return { requirements: requirementIds.size, acceptanceCriteria: acceptanceIds.size, tasks: tasks.length }; };
export const verifyTaskContract = async (taskId: string): Promise<{ taskId: string; evidenceHash: string }> => { const spec = await loadAndValidateSpecification(); const task = (await loadTasks()).find((item) => item.id === taskId); if (!task) throw new Error('TASK_NOT_FOUND'); if (JSON.stringify(task.sourceHashes) !== JSON.stringify(spec.hashes)) throw new Error('TASK_SOURCE_HASH_DRIFT'); for (const requirement of task.requirements) if (!spec.manifest.requirements.some((item) => item.id === requirement)) throw new Error(`UNKNOWN_REQUIREMENT:${requirement}`); for (const acceptance of task.acceptanceCriteria) if (!spec.manifest.acceptanceCriteria.some((item) => item.id === acceptance)) throw new Error(`UNKNOWN_ACCEPTANCE:${acceptance}`); return { taskId, evidenceHash: createHash('sha256').update(JSON.stringify(task)).digest('hex') }; };
export const verifyHarness = async (): Promise<Record<string, unknown>> => { const specification = await loadAndValidateSpecification(); const drift = await driftCheck(); const coverage = await verifyCoverage(); const architecture = await verifyArchitecture(); const placeholders = await scanPlaceholders(); const prohibited = await scanProhibitedCapabilities(); const tasks = await loadTasks(); if (tasks.length === 0) throw new Error('NO_TASK_CONTRACTS'); for (const task of tasks) TaskContractSchema.parse(task); return { sourceHashes: specification.hashes, drift, coverage, architecture, placeholders, prohibited, taskContracts: tasks.length }; };
