import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { access, mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { ClusterContractSchema, TaskContractSchema, TaskResultSchema, type ClusterContract, type TaskContract } from '@ciag/shared-schemas';
import { driftCheck, loadAndValidateSpecification, sha256, waitForCompilerIdle } from '../prd-compiler/compiler.js';
import { placeholderViolations, scanPlaceholders, scanProhibitedCapabilities, verifyArchitecture } from '../architecture-verifier/verify.js';
import { assertLease, readState, runtimeRoot, transition, writeState } from '../task-runner/state.js';
import { deriveAcceptanceMapping, deriveChangedFiles, deriveRequirementMapping, persistCommandEvidence, TASK_VERIFIER_VERSION, validateTaskAttestation, VERIFICATION_POLICY_VERSION } from './attestation.js';
import { verifyRuntimeBaseline } from './runtime-baseline.js';

export interface CommandEvidence { command: string; exitCode: number; output: string; outputSha256: string }
export const deriveEvidenceVerdict = (requiredCommands: string[], evidence: CommandEvidence[]): 'PASS' => { for (const command of requiredCommands) { const item = evidence.find((candidate) => candidate.command === command); if (!item) throw new Error(`MISSING_COMMAND_EVIDENCE:${command}`); if (item.exitCode !== 0) throw new Error(`COMMAND_FAILED:${command}`); if (sha256(item.output) !== item.outputSha256) throw new Error(`FORGED_COMMAND_EVIDENCE:${command}`); if (/^(?:PASS|ok|true)$/i.test(item.output.trim())) throw new Error(`UNSUBSTANTIATED_COMMAND_EVIDENCE:${command}`); } return 'PASS'; };

const git = (args: string[], cwd = process.cwd(), allowFailure = false): string => { const result = spawnSync('git', args, { cwd, encoding: 'utf8' }); if (result.status !== 0 && !allowFailure) throw new Error(`GIT_FAILED:${args.join(':')}:${result.stderr.trim()}`); return result.stdout.trim(); };
const run = (command: string, args: string[], cwd = process.cwd()): CommandEvidence => { const result = spawnSync(command, args, { cwd, encoding: 'utf8', env: process.env, maxBuffer: 32 * 1024 * 1024 }); const output = `${result.stdout ?? ''}${result.stderr ?? ''}`; return { command: [command, ...args].join(' '), exitCode: result.status ?? 1, output, outputSha256: sha256(output) }; };
const covers = (pattern: string, path: string): boolean => pattern.endsWith('/**') ? path === pattern.slice(0, -3) || path.startsWith(pattern.slice(0, -2)) : pattern === path;
const resultPath = (taskId: string, cwd = process.cwd()): string => join(runtimeRoot(cwd), 'results', `${taskId}.result.json`);

export const loadTasks = async (): Promise<TaskContract[]> => { await waitForCompilerIdle(); const tasks: TaskContract[] = []; for (let index = 0; index <= 7; index += 1) { const root = join(process.cwd(), `tasks/G${index}`); for (const file of await readdir(root)) if (file.endsWith('.contract.json')) tasks.push(TaskContractSchema.parse(JSON.parse(await readFile(join(root, file), 'utf8')))); } return tasks.sort((left, right) => left.id.localeCompare(right.id)); };
export const loadClusters = async (): Promise<ClusterContract[]> => { await waitForCompilerIdle(); const clusters: ClusterContract[] = []; for (let index = 0; index <= 7; index += 1) { const root = join(process.cwd(), `clusters/G${index}`); for (const file of await readdir(root)) if (file.endsWith('.contract.json')) clusters.push(ClusterContractSchema.parse(JSON.parse(await readFile(join(root, file), 'utf8')))); } return clusters.sort((left, right) => left.id.localeCompare(right.id)); };

export const verifyCoverage = async (): Promise<{ requirements: number; acceptanceCriteria: number; tasks: number }> => { const spec = await loadAndValidateSpecification(); const tasks = await loadTasks(); const requirementCounts = new Map<string, number>(); const acceptanceCounts = new Map<string, number>(); for (const task of tasks) { for (const id of task.requirements) requirementCounts.set(id, (requirementCounts.get(id) ?? 0) + 1); for (const id of task.acceptanceCriteria) acceptanceCounts.set(id, (acceptanceCounts.get(id) ?? 0) + 1); } const badRequirements = spec.manifest.requirements.filter((item) => requirementCounts.get(item.id) !== 1); const badAcceptance = spec.manifest.acceptanceCriteria.filter((item) => acceptanceCounts.get(item.id) !== 1); if (badRequirements.length || badAcceptance.length) throw new Error(`INCOMPLETE_OR_DUPLICATE_COVERAGE:R=${badRequirements.length}:A=${badAcceptance.length}`); return { requirements: requirementCounts.size, acceptanceCriteria: acceptanceCounts.size, tasks: tasks.length }; };

export const verifyTaskContract = async (taskId: string): Promise<{ taskId: string; evidenceHash: string }> => {
  const spec = await loadAndValidateSpecification(); const task = (await loadTasks()).find((item) => item.id === taskId); if (!task) throw new Error('TASK_NOT_FOUND'); if (JSON.stringify(task.sourceHashes) !== JSON.stringify(spec.hashes)) throw new Error('TASK_SOURCE_HASH_DRIFT');
  for (const requirement of task.requirements) if (!spec.manifest.requirements.some((item) => item.id === requirement)) throw new Error(`UNKNOWN_REQUIREMENT:${requirement}`);
  const acceptance = spec.manifest.acceptanceCriteria.filter((item) => task.acceptanceCriteria.includes(item.id)); for (const id of task.acceptanceCriteria) if (!acceptance.some((item) => item.id === id)) throw new Error(`UNKNOWN_ACCEPTANCE:${id}`);
  const expectedTests = [...new Set(acceptance.flatMap((item) => [item.positiveTestRef, item.negativeOrFailureTestRef]))]; if (JSON.stringify(task.requiredTests) !== JSON.stringify(expectedTests)) throw new Error(`TASK_TEST_MAPPING_DRIFT:${task.id}`);
  for (const path of task.writeSet) if (!task.allowedPaths.some((pattern) => covers(pattern, path.replace(/\/\*\*$/, '')) || pattern === path)) throw new Error(`WRITE_SET_OUTSIDE_ALLOWED:${task.id}:${path}`);
  if (task.changeBudget.maxMigrations === 0 && !task.forbiddenPaths.includes('infra/migrations/**')) throw new Error(`MIGRATION_OWNERSHIP_MISSING:${task.id}`);
  if (task.verificationCommands.some((item) => item.command.includes('task:verify'))) throw new Error(`RECURSIVE_TASK_VERIFICATION:${task.id}`);
  const index = JSON.parse(await readFile('tasks/generated/interface-hashes.json', 'utf8')) as Record<string, Record<string, string>>; if (JSON.stringify(index[task.id]) !== JSON.stringify(task.interfaceHashes)) throw new Error(`STALE_INTERFACE_HASH:${task.id}`);
  return { taskId, evidenceHash: createHash('sha256').update(JSON.stringify(task)).digest('hex') };
};

export const verifyTask = async (taskId: string, holder: string, leaseVersion: number): Promise<{ taskId: string; commit: string; evidenceHash: string }> => {
  const tasks = await loadTasks(); const task = tasks.find((item) => item.id === taskId); if (!task) throw new Error('TASK_NOT_FOUND'); await verifyTaskContract(taskId); const state = await readState(tasks); const target = assertLease(state, taskId, leaseVersion, holder, new Date()); if (!['SELF_REVIEWING', 'VERIFYING', 'VERIFIED', 'MERGE_QUEUED'].includes(target.state)) throw new Error(`SELF_REVIEW_REQUIRED:${target.state}`); const previousState = target.state;
  transition(target, ['SELF_REVIEWING', 'VERIFYING', 'VERIFIED', 'MERGE_QUEUED'], 'VERIFYING'); await writeState(state);
  try {
    const expectedBranch = `task/${taskId.toLowerCase()}`; const branch = git(['branch', '--show-current']); if (branch !== expectedBranch || target.branch !== expectedBranch) throw new Error(`TASK_BRANCH_MISMATCH:${branch}`);
    if (git(['status', '--porcelain', '--untracked-files=no']) !== '') throw new Error('DIRTY_TRACKED_SOURCE');
    const clusterBranch = `cluster/${task.dependencyGroup.toLowerCase()}`; const hasCluster = git(['show-ref', '--verify', `refs/heads/${clusterBranch}`], process.cwd(), true) !== ''; const base = hasCluster ? git(['rev-parse', clusterBranch]) : target.baseCommit; if (!base) throw new Error('TASK_BASE_COMMIT_MISSING');
    const commit = git(['rev-parse', 'HEAD']); if (commit === base) throw new Error('TASK_COMMIT_MISSING'); if (Number(git(['rev-list', '--count', `${base}..${commit}`])) !== 1) throw new Error('TASK_COMMIT_NOT_ATOMIC');
    const changed = git(['diff', '--name-only', `${base}..${commit}`]).split('\n').filter(Boolean); if (changed.length === 0) throw new Error('TASK_DIFF_EMPTY'); if (changed.length > task.complexityBudget.maxFiles) throw new Error('TASK_FILE_BUDGET_EXCEEDED');
    for (const path of changed) { if (task.forbiddenPaths.some((pattern) => covers(pattern, path))) throw new Error(`FORBIDDEN_PATH_CHANGE:${path}`); if (!task.allowedPaths.some((pattern) => covers(pattern, path))) throw new Error(`PATH_OUTSIDE_TASK_SCOPE:${path}`); }
    const changedLines = git(['diff', '--numstat', `${base}..${commit}`]).split('\n').filter(Boolean).reduce((sum, line) => sum + line.split('\t').slice(0, 2).reduce((count, value) => count + (Number(value) || 0), 0), 0); if (changedLines > task.complexityBudget.maxChangedLines) throw new Error('TASK_LINE_BUDGET_EXCEEDED');
    for (const path of task.requiredTests) { if (!path.startsWith('tests/') || path.includes('..')) throw new Error(`UNSAFE_TEST_PATH:${path}`); await access(path); const text = await readFile(path, 'utf8'); const violations = placeholderViolations(path, text); if (violations.length > 0) throw new Error(`INVALID_TASK_TEST:${violations.join(',')}`); }
    const commands: Array<[string, string[]]> = [['pnpm', ['exec', 'vitest', 'run', ...task.requiredTests]], ['pnpm', ['architecture:verify']], ['pnpm', ['placeholders:scan']], ['pnpm', ['prohibited-capabilities:scan']], ['pnpm', ['spec:verify']]]; const evidence = commands.map(([command, args]) => run(command, args)); deriveEvidenceVerdict(evidence.map((item) => item.command), evidence);
    const headTree = git(['rev-parse', 'HEAD^{tree}']); const changedFiles = deriveChangedFiles(base, commit); const commandEvidence = await persistCommandEvidence(taskId, commit, evidence); const reviewPath = join(runtimeRoot(), 'reviews', taskId, `${commit}.review.json`); const reviewText = await readFile(reviewPath, 'utf8'); if (!target.leaseId) throw new Error('LEASE_ID_MISSING'); const specification = await loadAndValidateSpecification(); const contractText = await readFile(`tasks/${task.dependencyGroup}/${task.id}.contract.json`, 'utf8');
    const result = TaskResultSchema.parse({ schemaVersion: '2.0.0', taskId, status: 'PASS', bindings: { taskContractSha256: sha256(contractText), prdSha256: specification.hashes.prd, requirementManifestSha256: specification.hashes.requirements, auditSha256: specification.hashes.audit, baseCommitSha: base, headCommitSha: commit, headTreeSha: headTree, changedFiles, requirementToCode: deriveRequirementMapping(task, changedFiles, commit), acceptanceToTests: await deriveAcceptanceMapping(task, commit), requiredTestArtifacts: commandEvidence.filter((item) => item.command.startsWith('pnpm exec vitest run ')), dependencyInterfaceHashes: task.interfaceHashes, verifierVersion: TASK_VERIFIER_VERSION, verificationPolicyVersion: VERIFICATION_POLICY_VERSION, leaseId: target.leaseId, leaseFencingVersion: target.leaseVersion, verificationTimestamp: new Date().toISOString(), selfReviewPath: `reviews/${taskId}/${commit}.review.json`, selfReviewSha256: sha256(reviewText) }, commandEvidence });
    await validateTaskAttestation(task, result, { currentHeadRequired: true, state: target }); const path = resultPath(taskId); await mkdir(dirname(path), { recursive: true }); await writeFile(path, `${JSON.stringify(result, null, 2)}\n`, { mode: 0o600 }); target.state = 'VERIFIED'; target.commit = commit; await writeState(state); return { taskId, commit, evidenceHash: sha256(JSON.stringify(result)) };
  } catch (error) { target.state = previousState === 'VERIFIED' || previousState === 'MERGE_QUEUED' ? previousState : 'SELF_REVIEWING'; await writeState(state); throw error; }
};

export const readTaskResult = async (taskId: string, cwd = process.cwd()): Promise<ReturnType<typeof TaskResultSchema.parse>> => TaskResultSchema.parse(JSON.parse(await readFile(resultPath(taskId, cwd), 'utf8')));

export const verifyHarness = async (): Promise<Record<string, unknown>> => {
  const specification = await loadAndValidateSpecification(); const drift = await driftCheck(); const coverage = await verifyCoverage(); const runtime = await verifyRuntimeBaseline(); const architecture = await verifyArchitecture(); const placeholders = await scanPlaceholders(); const prohibited = await scanProhibitedCapabilities(); const tasks = await loadTasks(); const clusters = await loadClusters();
  const taskIds = new Set(tasks.map((task) => task.id)); if (taskIds.size !== tasks.length) throw new Error('DUPLICATE_TASK_ID'); for (const task of tasks) { await verifyTaskContract(task.id); for (const dependency of task.dependencies) if (!taskIds.has(dependency)) throw new Error(`UNKNOWN_TASK_DEPENDENCY:${task.id}:${dependency}`); }
  const assignments = new Map<string, number>(); for (const cluster of clusters) { if (JSON.stringify(cluster.sourceHashes) !== JSON.stringify(specification.hashes)) throw new Error(`CLUSTER_SOURCE_HASH_DRIFT:${cluster.id}`); for (const taskId of cluster.tasks) assignments.set(taskId, (assignments.get(taskId) ?? 0) + 1); } if (tasks.some((task) => assignments.get(task.id) !== 1)) throw new Error('TASK_CLUSTER_ASSIGNMENT_INVALID');
  const semantic = JSON.parse(await readFile('artifacts/spec/semantic-stage.v1.json', 'utf8')) as Record<string, unknown>; const { artifactId, payloadSha256, liveModelCalls, ...payload } = semantic; const semanticHash = sha256(`${JSON.stringify(payload, null, 2)}\n`); if (payloadSha256 !== semanticHash || artifactId !== `semantic-stage-v1-${semanticHash}` || liveModelCalls !== false) throw new Error('SEMANTIC_ARTIFACT_INVALID');
  return { sourceHashes: specification.hashes, drift, coverage, runtime, architecture, placeholders, prohibited, taskContracts: tasks.length, clusterContracts: clusters.length, semanticArtifact: artifactId };
};
