import { readFile } from 'node:fs/promises';
import { describe, expect, it } from 'vitest';
import { UnavailableModelProvider } from '../../packages/agent-runtime/src/index.js';
import { matureSyntheticOutcome } from '@ciag/evaluation';
import { FakeObjectStore } from '@ciag/object-store';
import { InMemoryTracer } from '@ciag/observability';
import { applyBootstrapMigration } from '@ciag/persistence';
import { FakeNotificationTransport, FakeProviderNetwork, FakeQuotaClock, FakeWorkflowRuntime, MemoryPostgresAdapter, VirtualClock } from '@ciag/test-fixtures';
import { replayStagesAsOf, runWalkingSkeleton } from '@ciag/workflow-runtime';

describe('deterministic recovery and golden simulation', () => {
  it('recovers timeout, workflow crash, quota reset and model unavailability explicitly', async () => { const clock = new VirtualClock(); const provider = new FakeProviderNetwork(clock); provider.timeout = true; await expect(provider.discover(clock.now())).resolves.toMatchObject({ status: 'NOT_AVAILABLE', capabilityMode: 'SYNTHETIC_SHADOW' }); provider.timeout = false; await expect(provider.discover(clock.now())).resolves.toMatchObject({ status: 'AVAILABLE', capabilityMode: 'SYNTHETIC_SHADOW' }); const workflow = new FakeWorkflowRuntime(); workflow.crashNext = true; const started = await workflow.start({ idempotencyKey: 'same' }); await expect(workflow.resume(started.value?.runId ?? '')).resolves.toMatchObject({ value: { state: 'RESUMED' } }); const quota = new FakeQuotaClock(1); quota.charge(1); expect(quota.charge(1).reason).toBe('QUOTA_EXHAUSTED'); quota.reset(); expect(quota.charge(1).status).toBe('AVAILABLE'); await expect(new UnavailableModelProvider().generate()).resolves.toMatchObject({ status: 'NOT_AVAILABLE', capabilityMode: 'SYNTHETIC_SHADOW' }); });
  it('recovers an object-store failure without duplicating stages and preserves terminal notification retry', async () => { const database = new MemoryPostgresAdapter(); await applyBootstrapMigration(database); const clock = new VirtualClock(); const store = new FakeObjectStore(); store.failNext = true; const tracer = () => new InMemoryTracer(() => 'trace-replay', () => clock.now()); const dependencies = { database, objectStore: store, discovery: new FakeProviderNetwork(clock), notifications: new FakeNotificationTransport(), clock, tracer: tracer() }; await expect(runWalkingSkeleton(dependencies)).rejects.toThrow('INJECTED_OBJECT_STORE_FAILURE'); const recovered = await runWalkingSkeleton({ ...dependencies, tracer: tracer() }); expect(recovered.observationCount).toBe(6); const secondDatabase = new MemoryPostgresAdapter(); await applyBootstrapMigration(secondDatabase); const terminal = new FakeNotificationTransport(); terminal.failUntil = 2; const terminalResult = await runWalkingSkeleton({ database: secondDatabase, objectStore: new FakeObjectStore(), discovery: new FakeProviderNetwork(new VirtualClock()), notifications: terminal, clock: new VirtualClock(), tracer: new InMemoryTracer(() => 'trace-terminal') }); expect(terminalResult.outboxState).toBe('RETRY'); });
  it('excludes late observations from historical replay and matures only after virtual time', async () => { const database = new MemoryPostgresAdapter(); await applyBootstrapMigration(database); await database.query(`INSERT INTO synthetic_observations (id,asset_id,stage,payload_json,event_time,observed_at,available_at,idempotency_key,capability_mode,trace_id) VALUES ('late','asset','late','{}','2026-01-01','2026-01-03','2026-01-03','late-key','SYNTHETIC_SHADOW','trace-late')`); expect(await replayStagesAsOf(database, 'asset', '2026-01-02T00:00:00Z')).toEqual([]); expect(await replayStagesAsOf(database, 'asset', '2026-01-04T00:00:00Z')).toHaveLength(1); expect(matureSyntheticOutcome('2026-01-01T00:00:00Z', '2026-01-01T00:00:01Z', 2000).state).toBe('PENDING'); expect(matureSyntheticOutcome('2026-01-01T00:00:00Z', '2026-01-01T00:00:02Z', 2000).state).toBe('MATURE'); });
  it('keeps the required shared golden scenarios explicit and synthetic', async () => { const golden = JSON.parse(await readFile('test-data/golden-v1/cases.json', 'utf8')) as { capabilityMode: string; cases: { id: string }[] }; expect(golden.capabilityMode).toBe('SYNTHETIC_SHADOW'); const ids = golden.cases.map((item) => item.id); for (const id of ['duplicate-trigger', 'stale-lease', 'schema-drift', 'quota-exhaustion', 'object-store-failure', 'late-observation']) expect(ids).toContain(id); });
});
