import { bigint, boolean, index, integer, jsonb, pgTable, text, timestamp, uniqueIndex } from 'drizzle-orm/pg-core';

export const schemaMigrations = pgTable('schema_migrations', { version: text().primaryKey(), appliedAt: timestamp('applied_at', { withTimezone: true }).notNull() });
export const specificationMetadata = pgTable('specification_metadata', { id: text().primaryKey(), version: text().notNull(), prdSha256: text('prd_sha256').notNull(), manifestSha256: text('manifest_sha256').notNull(), auditSha256: text('audit_sha256').notNull(), recordedAt: timestamp('recorded_at', { withTimezone: true }).notNull() });
export const harnessState = pgTable('harness_state', { key: text().primaryKey(), valueJson: jsonb('value_json').notNull(), version: bigint({ mode: 'number' }).notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull() });
export const taskState = pgTable('task_state', { taskId: text('task_id').primaryKey(), state: text().notNull(), leaseVersion: bigint('lease_version', { mode: 'number' }).notNull(), leaseHolder: text('lease_holder'), leaseExpiresAt: timestamp('lease_expires_at', { withTimezone: true }), commitSha: text('commit_sha'), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull() });
export const clusterState = pgTable('cluster_state', { clusterId: text('cluster_id').primaryKey(), state: text().notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull() });
export const syntheticObservations = pgTable('synthetic_observations', { id: text().primaryKey(), assetId: text('asset_id').notNull(), stage: text().notNull(), payloadJson: jsonb('payload_json').notNull(), eventTime: timestamp('event_time', { withTimezone: true }).notNull(), observedAt: timestamp('observed_at', { withTimezone: true }).notNull(), availableAt: timestamp('available_at', { withTimezone: true }).notNull(), idempotencyKey: text('idempotency_key').notNull(), capabilityMode: text('capability_mode').notNull(), traceId: text('trace_id').notNull() }, (table) => [uniqueIndex('synthetic_observations_idempotency_idx').on(table.idempotencyKey), index('synthetic_observations_asset_available_idx').on(table.assetId, table.availableAt)]);
export const artifactMetadata = pgTable('artifact_metadata', { artifactKey: text('artifact_key').primaryKey(), sha256: text().notNull(), mediaType: text('media_type').notNull(), bytes: bigint({ mode: 'number' }).notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull(), frozen: boolean().notNull(), traceId: text('trace_id').notNull() });
export const outbox = pgTable('outbox', { id: text().primaryKey(), topic: text().notNull(), payloadJson: jsonb('payload_json').notNull(), state: text().notNull(), attemptCount: integer('attempt_count').notNull(), availableAt: timestamp('available_at', { withTimezone: true }).notNull(), deliveredAt: timestamp('delivered_at', { withTimezone: true }), traceId: text('trace_id').notNull() });
export const evaluationRecords = pgTable('evaluation_records', { id: text().primaryKey(), assetId: text('asset_id').notNull(), outcomeState: text('outcome_state').notNull(), signalSuccess: boolean('signal_success'), tradableSuccess: boolean('tradable_success'), evaluatedAt: timestamp('evaluated_at', { withTimezone: true }).notNull(), evidenceKey: text('evidence_key').notNull(), traceId: text('trace_id').notNull() });
export const auditRecords = pgTable('audit_records', { id: text().primaryKey(), eventType: text('event_type').notNull(), actor: text().notNull(), payloadJson: jsonb('payload_json').notNull(), previousHash: text('previous_hash'), recordHash: text('record_hash').notNull(), recordedAt: timestamp('recorded_at', { withTimezone: true }).notNull() });
export const triggerInbox = pgTable('trigger_inbox', { id: text().primaryKey(), source: text().notNull(), externalMessageId: text('external_message_id').notNull(), scheduleId: text('schedule_id'), scheduledFor: timestamp('scheduled_for', { withTimezone: true }), payloadHash: text('payload_hash').notNull(), receivedAt: timestamp('received_at', { withTimezone: true }).notNull(), verifiedAt: timestamp('verified_at', { withTimezone: true }), processedRunId: text('processed_run_id'), status: text().notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull() }, (table) => [uniqueIndex('trigger_inbox_external_message_id_idx').on(table.externalMessageId), index('trigger_inbox_schedule_idx').on(table.scheduleId, table.scheduledFor)]);
export const workflowRuns = pgTable('workflow_runs', { id: text().primaryKey(), workflowName: text('workflow_name').notNull(), scheduleId: text('schedule_id'), triggerInboxId: text('trigger_inbox_id'), status: text().notNull(), leaseOwner: text('lease_owner'), leaseVersion: bigint('lease_version', { mode: 'number' }).notNull(), leaseExpiresAt: timestamp('lease_expires_at', { withTimezone: true }), createdAt: timestamp('created_at', { withTimezone: true }).notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull(), completedAt: timestamp('completed_at', { withTimezone: true }), errorClass: text('error_class'), retryable: boolean() });
export const workflowSteps = pgTable('workflow_steps', { stepId: text('step_id').primaryKey(), runId: text('run_id').notNull(), stepType: text('step_type').notNull(), idempotencyKey: text('idempotency_key').notNull(), attempt: integer().notNull(), inputHash: text('input_hash').notNull(), outputHash: text('output_hash'), status: text().notNull(), leaseOwner: text('lease_owner'), leaseVersion: bigint('lease_version', { mode: 'number' }).notNull(), leaseExpiresAt: timestamp('lease_expires_at', { withTimezone: true }), startedAt: timestamp('started_at', { withTimezone: true }), completedAt: timestamp('completed_at', { withTimezone: true }), errorClass: text('error_class'), retryable: boolean().notNull(), nextRetryAt: timestamp('next_retry_at', { withTimezone: true }), createdAt: timestamp('created_at', { withTimezone: true }).notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull() }, (table) => [uniqueIndex('workflow_steps_idempotency_idx').on(table.idempotencyKey), index('workflow_steps_run_idx').on(table.runId, table.stepType)]);
export const stepAttempts = pgTable('step_attempts', { id: text().primaryKey(), stepId: text('step_id').notNull(), attempt: integer().notNull(), startedAt: timestamp('started_at', { withTimezone: true }).notNull(), completedAt: timestamp('completed_at', { withTimezone: true }), errorClass: text('error_class'), errorMessage: text('error_message'), retryable: boolean(), outputHash: text('output_hash') });
export const workflowLeases = pgTable('workflow_leases', { leaseKey: text('lease_key').primaryKey(), owner: text().notNull(), version: bigint({ mode: 'number' }).notNull(), acquiredAt: timestamp('acquired_at', { withTimezone: true }).notNull(), expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(), runId: text('run_id') });
export const deadLetterItems = pgTable('dead_letter_items', { id: text().primaryKey(), runId: text('run_id').notNull(), stepId: text('step_id'), errorClass: text('error_class').notNull(), retryable: boolean().notNull(), attempt: integer().notNull(), payloadJson: jsonb('payload_json'), errorMessage: text('error_message'), status: text().notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull(), resolvedAt: timestamp('resolved_at', { withTimezone: true }), lastRetryAt: timestamp('last_retry_at', { withTimezone: true }) });
export const alerts = pgTable('alerts', { alertId: text('alert_id').primaryKey(), assetId: text('asset_id').notNull(), alertClass: text('alert_class').notNull(), actionabilityState: text('actionability_state').notNull(), fingerprint: text('fingerprint').notNull(), validUntil: timestamp('valid_until', { withTimezone: true }).notNull(), payloadJson: jsonb('payload_json').notNull(), canonicalJson: text('canonical_json').notNull(), sha256: text('sha256').notNull(), bytes: integer('bytes').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull(), shadowMode: boolean('shadow_mode').notNull().default(false), traceId: text('trace_id').notNull() }, (table) => [index('alerts_asset_class_idx').on(table.assetId, table.alertClass), index('alerts_fingerprint_idx').on(table.fingerprint)]);
