import { bigint, boolean, index, integer, jsonb, pgTable, text, timestamp, uniqueIndex } from 'drizzle-orm/pg-core';

export const schemaMigrations = pgTable('schema_migrations', { version: text().primaryKey(), appliedAt: timestamp('applied_at', { withTimezone: true }).notNull() });
export const specificationMetadata = pgTable('specification_metadata', { id: text().primaryKey(), version: text().notNull(), prdSha256: text('prd_sha256').notNull(), manifestSha256: text('manifest_sha256').notNull(), auditSha256: text('audit_sha256').notNull(), recordedAt: timestamp('recorded_at', { withTimezone: true }).notNull() });
export const harnessState = pgTable('harness_state', { key: text().primaryKey(), valueJson: jsonb('value_json').notNull(), version: bigint({ mode: 'number' }).notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull() });
export const taskState = pgTable('task_state', { taskId: text('task_id').primaryKey(), state: text().notNull(), leaseVersion: bigint('lease_version', { mode: 'number' }).notNull(), leaseHolder: text('lease_holder'), leaseExpiresAt: timestamp('lease_expires_at', { withTimezone: true }), commitSha: text('commit_sha'), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull() });
export const clusterState = pgTable('cluster_state', { clusterId: text('cluster_id').primaryKey(), state: text().notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull() });
export const syntheticObservations = pgTable('synthetic_observations', { id: text().primaryKey(), assetId: text('asset_id').notNull(), stage: text().notNull(), payloadJson: jsonb('payload_json').notNull(), eventTime: timestamp('event_time', { withTimezone: true }).notNull(), observedAt: timestamp('observed_at', { withTimezone: true }).notNull(), availableAt: timestamp('available_at', { withTimezone: true }).notNull(), idempotencyKey: text('idempotency_key').notNull(), capabilityMode: text('capability_mode').notNull(), traceId: text('trace_id').notNull() }, (table) => [uniqueIndex('synthetic_observations_idempotency_idx').on(table.idempotencyKey), index('synthetic_observations_asset_available_idx').on(table.assetId, table.availableAt)]);
export const artifactMetadata = pgTable('artifact_metadata', { artifactKey: text('artifact_key').primaryKey(), sha256: text().notNull(), mediaType: text('media_type').notNull(), bytes: bigint({ mode: 'number' }).notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull(), frozen: boolean().notNull(), traceId: text('trace_id').notNull() });
export const outbox = pgTable('outbox', { id: text().primaryKey(), topic: text().notNull(), payloadJson: jsonb('payload_json').notNull(), state: text().notNull(), attemptCount: integer('attempt_count').notNull(), availableAt: timestamp('available_at', { withTimezone: true }).notNull(), deliveredAt: timestamp('delivered_at', { withTimezone: true }), traceId: text('trace_id').notNull() });
export const evaluationRecords = pgTable('evaluation_records', { id: text().primaryKey(), assetId: text('asset_id').notNull(), outcomeState: text('outcome_state').notNull(), signalSuccess: boolean('signal_success'), tradableSuccess: boolean('tradable_success'), evaluatedAt: timestamp('evaluated_at', { withTimezone: true }).notNull(), evidenceKey: text('evidence_key').notNull(), traceId: text('trace_id').notNull() });
export const auditRecords = pgTable('audit_records', { id: text().primaryKey(), eventType: text('event_type').notNull(), actor: text().notNull(), payloadJson: jsonb('payload_json').notNull(), previousHash: text('previous_hash'), recordHash: text('record_hash').notNull(), recordedAt: timestamp('recorded_at', { withTimezone: true }).notNull() });
