import { describe, expect, it } from 'vitest';
import { createApp } from '../../apps/api/src/app.js';

describe('API shell', () => {
  const app = createApp({ allowedOrigins: ['https://allowed.example'], dependencies: [{ name: 'database', ready: async () => true, detail: 'synthetic' }], now: () => '2026-01-01T00:00:00.000Z' });
  it('separates liveness and readiness', async () => { expect((await app.request('/api/v1/health')).status).toBe(200); const response = await app.request('/api/v1/readiness'); expect(response.status).toBe(200); expect((await response.json()).capabilityMode).toBe('SYNTHETIC_SHADOW'); });
  it('rejects invalid MCP origin before execution', async () => { const response = await app.request('/mcp', { method: 'POST', headers: { origin: 'https://evil.example', 'content-type': 'application/json' }, body: JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'tools/list' }) }); expect(response.status).toBe(403); });
  it('requires an origin and bounds MCP payload size', async () => { const missing = await app.request('/mcp', { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{}' }); expect(missing.status).toBe(403); const bounded = createApp({ allowedOrigins: ['https://allowed.example'], mcpMaxBodyBytes: 1024, dependencies: [] }); const large = await bounded.request('/mcp', { method: 'POST', headers: { origin: 'https://allowed.example', 'content-type': 'application/json' }, body: JSON.stringify({ value: 'x'.repeat(2048) }) }); expect(large.status).toBe(413); });
  it('fails closed when MCP bearer authentication is configured', async () => { const authenticated = createApp({ allowedOrigins: ['https://allowed.example'], mcpAuthToken: 'secret-bootstrap-token', dependencies: [] }); const response = await authenticated.request('/mcp', { method: 'POST', headers: { origin: 'https://allowed.example', 'content-type': 'application/json' }, body: '{}' }); expect(response.status).toBe(401); expect((await response.json()).error.code).toBe('UNAUTHORIZED'); });
  it('bounds tracked MCP client identities', async () => { const bounded = createApp({ allowedOrigins: ['https://allowed.example'], mcpMaxTrackedClients: 1, dependencies: [] }); const first = await bounded.request('/mcp', { method: 'POST', headers: { origin: 'https://allowed.example', 'content-type': 'application/json', 'x-mcp-client-id': 'first' }, body: '{}' }); expect(first.status).not.toBe(429); const second = await bounded.request('/mcp', { method: 'POST', headers: { origin: 'https://allowed.example', 'content-type': 'application/json', 'x-mcp-client-id': 'second' }, body: '{}' }); expect(second.status).toBe(429); });
  it('turns readiness rejection and timeout into not-ready dependency state', async () => { const bounded = createApp({ allowedOrigins: [], readinessTimeoutMs: 5, dependencies: [{ name: 'rejecting', ready: async () => { throw new Error('down'); }, detail: 'check' }, { name: 'hanging', ready: () => new Promise(() => undefined), detail: 'check' }] }); const response = await bounded.request('/api/v1/readiness'); expect(response.status).toBe(503); expect((await response.json()).dependencies).toEqual([{ name: 'rejecting', ready: false, detail: 'check: check-failed' }, { name: 'hanging', ready: false, detail: 'check: unavailable-or-timeout' }]); });
  it('serves a read-only MCP tool contract over the official Streamable HTTP transport', async () => { const response = await app.request('/mcp', { method: 'POST', headers: { origin: 'https://allowed.example', 'content-type': 'application/json', accept: 'application/json, text/event-stream', 'mcp-protocol-version': '2025-11-25' }, body: JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'tools/list' }) }); expect(response.status).toBe(200); expect(JSON.stringify(await response.json())).toContain('system_readiness'); });
});
